### ISSUE TITLE
Support for non root unity projects

### ISSUE THREAD

**Issue by simeonradivoev** [simeonradivoev/UniGit#27]
Support for repositories that don't have the asset folder as a root the the repository. For example a unity project that's in a subfolder of the repository.

**Comment by JeReT** [comment]
I always have my projects like this or similar:
> git root folder
-> unity root folder
-> documents
-> game design
-> builds (ignored by git)

so, that I have things which belong to the project (like game design excel tables or documents which usually explain some technical setup stuff) beneath the root next to the actual unity project.
It turned out to be a good way to manage projects for me.

So, I really need this feature to use your plugin.
And I really want to use your plugin so that (technical) artists don't have to dive into git too much,..
