### ISSUE TITLE
Support for plain old git?

### ISSUE THREAD

**Issue by angusmf** [simeonradivoev/UniGit#32]
Since use of an external git adapter is recommended, I was curious about the lack of support for the "normal" git executable that is usually added to PATH (which seems to be how you're doing LFS.) Is there a limitation requiring use of lib2gitSharp or these other programs? I looked at the existing adapters and it seems like it would work ok, and probably then work on linux and mac.

**Comment by simeonradivoev** [comment]
I recommend external apps just because they should be more tested with more users. Using just UniGit should be just fine. In fact I use it for developing UniGit itself.
As for LFS I just can't get enough documentation oh now to use it with lib2gitSharp, that's why for example it doesn't work with multithreaded staging and commits.

**Comment by simeonradivoev** [comment]
And yes using lib2gitSharp is much more simple and reliable than using the git exe. I will have to write all sort of boilerplate codes.

**Comment by angusmf** [comment]
Thanks. I was curious because the adapters were windows-only, and have noticed some functionality lib2gitSharp doesn't have while attempting to do some automation code.
